"""add job priority

Revision ID: 5aebf12d5546
Revises: b4422e1d059d
Create Date: 2025-12-08 18:23:50.087246
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5aebf12d5546"
down_revision = "b4422e1d059d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "priority_class",
                sa.Enum("low", "medium", "high", "extra-high", name="jobpriority"),
                server_default="medium",
                nullable=False,
            )
        )
        batch_op.alter_column(
            "gpu_profile",
            existing_type=sa.VARCHAR(length=5),
            type_=sa.Enum(
                "1g.10gb", "2g.20gb", "3g.40gb", "4g.40gb", "7g.79gb", name="gpuprofile"
            ),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.alter_column(
            "gpu_profile",
            existing_type=sa.Enum(
                "1g.10gb", "2g.20gb", "3g.40gb", "4g.40gb", "7g.79gb", name="gpuprofile"
            ),
            type_=sa.VARCHAR(length=5),
            existing_nullable=False,
        )
        batch_op.drop_column("priority_class")

    # ### end Alembic commands ###
