"""JobRuns unique fields

Revision ID: 74344afe75c2
Revises: a05d3fd91d8d
Create Date: 2025-10-30 00:20:45.219529
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "74344afe75c2"
down_revision = "a05d3fd91d8d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_runs", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_job_runs_k8s_job_name", ["k8s_job_name"])
        batch_op.create_unique_constraint("uq_job_runs_k8s_pod_name", ["k8s_pod_name"])
        batch_op.drop_column("exit_code")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_runs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("exit_code", sa.INTEGER(), nullable=True))
        batch_op.drop_constraint("uq_job_runs_k8s_pod_name", type_="unique")
        batch_op.drop_constraint("uq_job_runs_k8s_job_name", type_="unique")

    # ### end Alembic commands ###
