"""add secret_names

Revision ID: 91462034ac11
Revises: 5aebf12d5546
Create Date: 2025-12-08 22:35:12.319281
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "91462034ac11"
down_revision = "5aebf12d5546"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_runs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "secret_names",
                sa.JSON(),
                nullable=False,
                server_default="[]",
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_runs", schema=None) as batch_op:
        batch_op.drop_column("secret_names")

    # ### end Alembic commands ###
