"""move k8s_job_name from Job to JobRuns

Revision ID: a05d3fd91d8d
Revises: 0001_initial_schema
Create Date: 2025-10-29 21:13:41.475648
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a05d3fd91d8d"
down_revision = "0001_initial_schema"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_runs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("k8s_job_name", sa.String(), nullable=False))

    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.alter_column(
            "gpu_profile",
            existing_type=sa.VARCHAR(length=7),
            type_=sa.Enum(
                "g1_10", "g2_20", "g3_40", "g4_40", "g7_79", name="gpuprofile"
            ),
            existing_nullable=False,
        )
        batch_op.drop_column("k8s_job_name")

    with op.batch_alter_table("personal_access_tokens", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_personal_access_tokens_token_hash"),
            ["token_hash"],
            unique=True,
        )

    with op.batch_alter_table("social_identities", schema=None) as batch_op:
        batch_op.alter_column(
            "email_verified",
            existing_type=sa.BOOLEAN(),
            server_default=None,
            existing_nullable=False,
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "role",
            existing_type=sa.VARCHAR(),
            server_default=None,
            existing_nullable=False,
        )

    with op.batch_alter_table("volumes", schema=None) as batch_op:
        batch_op.alter_column(
            "is_input",
            existing_type=sa.BOOLEAN(),
            server_default=None,
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("volumes", schema=None) as batch_op:
        batch_op.alter_column(
            "is_input",
            existing_type=sa.BOOLEAN(),
            server_default=sa.text("0"),
            existing_nullable=False,
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "role",
            existing_type=sa.VARCHAR(),
            server_default=sa.text("'admin'"),
            existing_nullable=False,
        )

    with op.batch_alter_table("social_identities", schema=None) as batch_op:
        batch_op.alter_column(
            "email_verified",
            existing_type=sa.BOOLEAN(),
            server_default=sa.text("0"),
            existing_nullable=False,
        )

    with op.batch_alter_table("personal_access_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_personal_access_tokens_token_hash"))

    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("k8s_job_name", sa.VARCHAR(), nullable=False))
        batch_op.alter_column(
            "gpu_profile",
            existing_type=sa.Enum(
                "g1_10", "g2_20", "g3_40", "g4_40", "g7_79", name="gpuprofile"
            ),
            type_=sa.VARCHAR(length=7),
            existing_nullable=False,
        )

    with op.batch_alter_table("job_runs", schema=None) as batch_op:
        batch_op.drop_column("k8s_job_name")

    # ### end Alembic commands ###
