"""remove state from Volume model

Revision ID: b4422e1d059d
Revises: 74344afe75c2
Create Date: 2025-11-03 19:34:51.978656
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b4422e1d059d"
down_revision = "74344afe75c2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("volumes", schema=None) as batch_op:
        batch_op.drop_column("state")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("volumes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("state", sa.VARCHAR(length=7), nullable=False))

    # ### end Alembic commands ###
